### PR TITLE
Dev/episode1

### PR DESCRIPTION
**Pull request by DeanFaizal**
Created the app structure, base twitch service.

### CODE REVIEW

**Review by Sweekriti91 — CHANGES_REQUESTED** [review]
Something really weird is happening when I did a git pull. I fixed the issues i hit with UITest. but in the Android project, the Resources folder is missing. I keep hitting build errors. but when I fixed the errors locally by copying over the files from a blank Shell template, it builds locally for me. BUT git is not picking up the changes to commit. @DeanFaizal  want to take a look what's going on? I'll continue trying from my end.

**Comment by Sweekriti91** [comment]
okay wait found it, why are we ignoring the full `XamTwitch/XamTwitch\.Android/Resources/` folder? i think the `.gitignore` should be for that one `Resources.Designer.cs` that gets auto generated. I'm updating the `.gitignore` and pushing it. someone comment if you have issues.

**Review by Sweekriti91 — CHANGES_REQUESTED** [review]
Okay fixed the Android build issues and updated the `.gitignore` I'm updating the build pipeline to enable PR checks and will wait for that to pass before I approve this. Anyone else want to take a look as well?

**Review by Sweekriti91 — APPROVED** [review]
Approved with OG PR + changes made by me :

- made some fixes to the UITest project
- updated `.gitignore` because it was causing build fails on Android 
- updated pr-check pipeline and added nuget.config for local nuget restore 
- PR check enabled and passed

I'm good to merge this now.

**Review by BenBtg — CHANGES_REQUESTED** [review]
My only comment is regarding checking in nupkgs. If we need the local packages in the repo can we switch them to LFS?

**Comment by Sweekriti91** [comment]
@BenBtg  we can remove the nugets from the repo completely. For DevOps I can add a task to download the nuget from the GitReleases. We can leave that folder, delete the nugets from git and instead add a Readme with steps to setup the local nuget feed? what do you think?

**Comment by DeanFaizal** [comment]
I like that idea @Sweekriti91. Removes the lib from having a ‘floating’ version in this repo.

**Comment by DeanFaizal** [comment]
Actually github packages are available today so we can just migrate to that :)

**Comment by DeanFaizal** [comment]
Github packages isn't ready for us to migrate mobcat-lib to (note it's still in beta). It works on Windows but not on Mac. Both adding a source through cli and consuming source in VS Mac fails. An issue will be opened with GitHub. Use local packages until this is resolved.

**Pull request merged**
